### ISSUE TITLE
Cut list file format

### ISSUE THREAD

**Issue by LorenzoinNC** [space10-community/the-growroom#10]
Any chance that the cut list and plans will be issued in a format other than UNIX? A plain pdf, for example.

**Comment by danielfriis** [comment]
Hi LorenzionNC. We’ve decided just to release it in the two most commonly used formats used in digital fabrication. They are not available in pdf as we wouldn’t recommend to cut the pavilion with jigsaw or other manual tools that are not hooked up to anything digital. Firstly, because it‘s hard to avoid making splits. Second, because each part needs to be cut very precisely and small inaccuracies will do that things do not fit together properly, or offset in relation to the upper layers.
