### ISSUE TITLE
Plywood Thickness and Imperial vs. Metric Measurements

### ISSUE THREAD

**Issue by n8martin22** [space10-community/the-growroom#11]
Here is the USA we use imperial measurements and thus finding plywood that meets the 18mm thickness will either be slightly off (.688 inches or 17.475mm) or prohibitively expensive to purchase (imported birch faced at $40 USD/sheet). Will using a slightly smaller thickness material affect the product's assembly or design integrity?

**Comment by dahousecat** [comment]
I didn't design this (and have not built it), however from looking at the instructions I can see that there are slots in the design where sheets need to fit (ideally) tightly in the slot. If you use different width plywood you'll need to adjust the width of these slots to match. 
From having made lots of plywood structures in the past I can't imagine that taking half a millimetre of the thickness of the board used would affect the overall integrity of the structure.

**Comment by silicakes** [comment]
I'm getting the same cost for birch (I'm from Israel), but I reckon it's due to the fact that it's being imported from Europe (Russia mostly) - so it does make sense.

**Comment by cwiegman** [comment]
I am using the 23/32 nominal size listed at 3/4 in the store --- i think they are mislabeled. This gets be to about 0.65 inches ($34/sheet before tax)

**Comment by cwiegman** [comment]
Turns out the boards had issues with being too tight of a fit. They did have stamps on them to be a 23/32 board. and measured that way, but I had to Dremel to grind wider openings in a few places and mallet a few tight fits where I wish I had just CNCed an extra 0.1" offset.

**Comment by HusumLindholm** [comment]
There is an overall tolerance in all slots and connections of 1mm, in order to make assembly as easy as possible. 
Depending on the quality of the plywood you choose, the thickness throughout each sheet of plywood can vary with between 1-2mm. We experienced this when we tested the Growroom with a cheap plywood consisting of few layers.

In the case of not being able to get an 18mm plywood, I suggest that you scale the drawings for that. For instance, if your sheets are 18.5mm in thickness, scale all drawings (18.5/18).

The drawings have been updated, and you can now find a package with each sheet laid out as well as a file consisting of all the sheets. 

Best regards
Husum&Lindholm

**Comment by mhasting2004** [comment]
Another metric/imperial issue even down here in Australia is that a 3/8" or 9.5mm compression bit is much more standard than a 8mm. This means the corner reliefs should also be large (I'd suggest 10mm diameter reather than the existing 8mm. I'm modifing the files for my machin  but its not something everyone would spot or be able to do before sending the DXF's to a local CNC shop.
