### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by martinszy** [space10-community/the-growroom#3]
I have seen the building manual, but I think another document with recommendations on how to use, like appropriate techniques, soil, seeds, watering and other usage instructions could be useful.
I know this might vary according to location, but some of the instructions could be universal.

**Comment by danielfriis** [comment]
Hi Martinszy, yes it very much depends on individual environments and climates so we recommend reaching out to local specialists, who can guide you in what’s best to use for your local environment. However since we’ve received lot of similar questions from others we are currently looking into how we can optimise the manual when it comes it instructions that are universal.
